#!/bin/sh
# Regenerates the files of images/incus-support that come from the Incus
# project (the agent setup script, the systemd unit and the udev rule) from
# the release pinned in images/incus-support/incus-agent.pin.
#
# Usage: hack/sync-incus-agent.sh
#
# It downloads the files at the pinned commit from raw.githubusercontent.com,
# replaces upstream's TARGET placeholder (which its install script fills in)
# with /usr/lib, prepends a generated header naming the file's origin, and
# writes them with their modes. Running it again with an unchanged pin
# changes nothing. Needs curl; works with GNU and BSD tools.
set -eu

root="$(cd "$(dirname "$0")/.." && pwd)"
image="${root}/images/incus-support"
pin="${image}/incus-agent.pin"
loader=internal/server/instance/drivers/agent-loader

pin_value() {
	sed -n "s/^$1=//p" "${pin}"
}
tag="$(pin_value INCUS_TAG)"
commit="$(pin_value INCUS_COMMIT)"
case "${commit}" in
*[!0-9a-f]* | "")
	echo "error: INCUS_COMMIT in ${pin} must be a full commit SHA" >&2
	exit 1
	;;
esac
if [ "${#commit}" -ne 40 ] || [ -z "${tag}" ]; then
	echo "error: ${pin} needs INCUS_TAG and a 40-character INCUS_COMMIT" >&2
	exit 1
fi

work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT

# generate <upstream file under agent-loader> <destination under the image> <mode> <comment prefix>
generate() {
	upstream="$1"
	dest="${image}/$2"
	mode="$3"
	url="https://raw.githubusercontent.com/lxc/incus/${commit}/${loader}/${upstream}"

	curl -fsSL -o "${work}/src" "${url}"
	sed 's#TARGET#/usr/lib#g' "${work}/src" >"${work}/body"
	if grep -q TARGET "${work}/body"; then
		echo "error: ${upstream} still contains TARGET after substitution" >&2
		exit 1
	fi

	{
		# A script keeps its shebang on the first line.
		if [ "$(head -c 2 "${work}/body")" = '#!' ]; then
			head -n 1 "${work}/body"
			sed 1d "${work}/body" >"${work}/rest"
		else
			cp "${work}/body" "${work}/rest"
		fi
		cat <<HEADER
# Generated by hack/sync-incus-agent.sh from the Incus project
# (https://github.com/lxc/incus, Apache-2.0); do not edit.
#   ${loader}/${upstream}
#   release ${tag}, commit ${commit}
# Changed from upstream: this header and, where the file has it, the TARGET
# placeholder resolved to /usr/lib.
HEADER
		cat "${work}/rest"
	} >"${work}/out"

	mkdir -p "$(dirname "${dest}")"
	cp "${work}/out" "${dest}"
	chmod "${mode}" "${dest}"
	echo "wrote ${dest#"${root}"/}"
}

generate incus-agent-setup-linux systemd/usr/lib/systemd/incus-agent-setup 755
generate systemd/incus-agent.service systemd/usr/lib/systemd/system/incus-agent.service 644
generate systemd/incus-agent.rules systemd/usr/lib/udev/rules.d/99-incus-agent.rules 644
generate incus-agent-setup-linux openrc/usr/local/bin/incus-agent-setup 755
